In [1]:
import numpy as np

In [2]:
#Stack arrays vertically

a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2])
print(stacked)


[[1 2]
 [3 4]]


In [3]:
#Stack arrays horizontally
stacked = np.hstack([a2,b2])
print(stacked)

[1 2 3 4]


Mathematical Functions

In [4]:
#Add 2 arrays
g = np.array([1,2,3,4])
added = np.add(g,2)
print(added)

[3 4 5 6]


In [6]:
#Squared each element
square = np.power(g,2)
print(square)

[ 1  4  9 16]


In [8]:
#Square root of each element
root = np.sqrt(g)
print(root)

[1.         1.41421356 1.73205081 2.        ]


In [11]:
#Dot product of 2 arrays
a3=np.array([4,5,6,7])
dot = np.dot(g,a3)
print(dot)

60


Statistics Function

In [12]:
#Mean of array
mean = np.mean(a3)
print(mean)

5.5


In [13]:
# Variance of array
vari = np.var(a3)
print(a3)

[4 5 6 7]


In [14]:
# Standard Deviation of Array
sd = np.std(a3)
print(sd)

1.118033988749895


In [15]:
# Min element of array
mini = np.min(a3)
print(mini)

4


In [16]:
# Max element of Array
maxi = np.max(a3)
print(maxi)

7


Random Sampling Function

In [18]:
rand = np.random.rand(3) #Prints array of 3 random values
print(rand)

[0.11897329 0.48684139 0.21655782]


In [20]:
np.random.seed(0) # Does not change the random values
randints = np.random.randint(0,10,size=6)
print(randints)

[5 0 3 3 7 9]


Boolean And Logical Functions

In [21]:
# Check if all elements are true
#all
logi = np.array([True,False,True])
all_True = np.all(logi) # Check if all are true
print(all_True)

False


In [22]:
# Check if all elements are true
#all
logi = np.array([False,False,False])
all_True = np.all(logi) # Check if all are true
print(all_True)

False


In [23]:
#any
any_true = np.any(logi) # Check if any is True
print(any_true)

False


Set operations

In [2]:
import numpy as np
set1 = np.array([1,2,3,4])
set2 = np.array([3,4,5,6])
inter = np.intersect1d(set1,set2)
print(inter)

[3 4]


In [3]:
union = np.union1d(set1,set2)
print(union)

[1 2 3 4 5 6]


Array Attribute Functions

In [4]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


Other Functions

In [5]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [6]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [7]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
