NumPy Crash Course


In [1]:
import numpy as np

In [3]:
np.__version__

'2.3.5'

In [6]:
my_list = [0,1,2,3,4,5] #create a list

In [7]:
type(my_list)

list

In [12]:
arr = np.array(my_list) # Converting list to array
arr

array([0, 1, 2, 3, 4, 5])

In [13]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [15]:
np.arange(10)  # Prints 0 to 9 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(10,20) # Prints 10 to 19

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(10,50,5) #Counts 5 steps--- max we can pass 3 arguments

array([10, 15, 20, 25, 30, 35, 40, 45])

In [21]:
np.arange(20,10) #Empty

array([], dtype=int64)

In [25]:
np.zeros(3) #1D array--- float output

array([0., 0., 0.])

In [26]:
np.zeros(3, dtype = int) # Hyper parameter tuning -- int output

array([0, 0, 0])

In [27]:
np.zeros([2,2]) #2D array

array([[0., 0.],
       [0., 0.]])

In [28]:
np.zeros([10,10],dtype=int) # n-D array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [29]:
np.ones(4)

array([1., 1., 1., 1.])

In [30]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [31]:
np.random.rand(3) # Prints 3 random values

array([0.86653463, 0.86549603, 0.18729149])

In [32]:
np.random.rand(3,4) #2d array random values

array([[0.6182499 , 0.33615667, 0.11574037, 0.86442602],
       [0.43769059, 0.18356669, 0.66169264, 0.8487456 ],
       [0.20870722, 0.35841393, 0.32858578, 0.40393653]])

In [37]:
np.random.randint(3) # Integer

1

In [38]:
np.random.randint(10,20) # Random integers btw 10 to 19

16

In [40]:
np.random.randint(1,10,4) # Generate 4 random numbers between 1 to 10

array([6, 3, 5, 8])

In [41]:
np.random.randint(1,10,(10,10)) #Print 10 rows and 10 coloums-- 10*10 matrix

array([[7, 8, 9, 2, 4, 2, 3, 9, 5, 3],
       [4, 2, 9, 2, 3, 1, 4, 7, 7, 7],
       [1, 7, 4, 2, 9, 2, 8, 6, 6, 3],
       [1, 9, 6, 2, 3, 4, 9, 9, 6, 5],
       [4, 1, 4, 3, 8, 5, 9, 5, 9, 2],
       [2, 3, 8, 2, 8, 7, 7, 3, 2, 2],
       [3, 5, 3, 6, 6, 6, 9, 5, 6, 5],
       [8, 5, 4, 9, 1, 7, 4, 4, 7, 8],
       [4, 3, 8, 5, 7, 3, 1, 2, 1, 4],
       [3, 5, 7, 5, 5, 4, 2, 8, 8, 5]])

In [44]:
np.random.randint(1,10,(4,6)) # Random values of 1 to 9 in matrix of 4*6

array([[8, 4, 5, 7, 8, 5],
       [1, 1, 1, 3, 4, 1],
       [9, 5, 4, 9, 9, 4],
       [3, 7, 3, 7, 7, 6]])

In [47]:
m = np.random.randint(1,10,(4,6))
m

array([[4, 8, 5, 2, 3, 1],
       [1, 6, 2, 8, 8, 9],
       [4, 9, 6, 7, 1, 7],
       [9, 9, 4, 3, 3, 4]])

In [48]:
m[0] # prints first row

array([4, 8, 5, 2, 3, 1])

In [49]:
m[0] = [1,2,3,4,5,6] # manipulating or updating row 1
m

array([[1, 2, 3, 4, 5, 6],
       [1, 6, 2, 8, 8, 9],
       [4, 9, 6, 7, 1, 7],
       [9, 9, 4, 3, 3, 4]])

In [53]:
print(m[0,4]) #prints 5th element in 1st row


5


In [55]:
print(m[-2,-3])

7
